Updated deploy.yml for port 8000

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -35,3 +35,14 @@ jobs:
             echo "Starting new container on port 8000..."
             docker run -d --name go-app -p 8000:8000 navaneetha084/go-app:latest
             echo "Deployment successful!"
+
+      - name: Verify Deployment
+        run: |
+          echo "Verifying if the app is running..."
+          response=$(curl -s -o /dev/null -w "%{http_code}" http://$${{ secrets.EC2_HOST }}:8000)
+          if [ "$response" -eq 200 ]; then
+            echo "App is successfully deployed!"
+          else
+            echo "Failed to deploy the app. Response code: $response"
+            exit 1
+          fi
